Repository GDSC-BSIOTR/LAPTECHNO, pull requests merged in 2022-09, with the labels that each got.

#23 Update laptech.txt
  laptech.txt
Labels: hactoberfest-accepted

#25 updated info
  laptech.txt
Labels: hactoberfest-accepted

#26 Added laptop info
  laptech.txt
Labels: hactoberfest-accepted

#27 added 88
  laptech.txt
Labels: hactoberfest-accepted

#29 Update laptech.txt
  laptech.txt
Labels: hactoberfest-accepted

#30 Update laptech.txt
  laptech.txt
Labels: hactoberfest-accepted

#31 lenovo added
  laptech.txt
Labels: hactoberfest-accepted

#32 added dell laptop with 10th gen
  laptech.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#33 Updated
  laptech.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#34 laptop info added
  laptech.txt
Labels: hactoberfest-accepted, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#35 update info
  laptech.txt
Labels: hactoberfest-accepted, hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#37 new
  laptech.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#39 Revert "Update laptech.txt"
  laptech.txt
Labels: hacktoberfest, hacktoberfest-accepted, hacktober-accepted

#40 Changes done
  laptech.txt
Labels: hactoberfest-accepted, hacktoberfest, hacktoberfest-accepted, hacktober-accepted
